### PR TITLE
Remove application@label attribute from Android manifest

### PR DESCRIPTION
**Pull request by al-broco**
Suggestion for a fix of issue #5 .

### CODE REVIEW

**Comment by westwest128** [comment]
Merged

**Comment by Bozo55** [comment]
Thanks

**Review by Stretch379 — APPROVED** [review]

**Comment by COST1R8M** [comment]
[](url)https://go.shr.lc/3V5QCN1

**Comment by COST1R8M** [comment]
> https://go.shr.lc/3V5QCN1

www.samsung.com

**Pull request merged**
