### PR TITLE
Api_Azure devcontainer.json

### PR DESCRIPTION
**Pull request by chomsin**
- #75

### CODE REVIEW

**Comment by chomsin** [comment]
- no #76

**Comment by chomsin** [comment]
> [CLA assistant check](https://cla-assistant.io/NordicSemiconductor/nRF-Logger-API?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NordicSemiconductor/nRF-Logger-API?pullRequest=77) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicSemiconductor/nRF-Logger-API?pullRequest=77) it.</sub>

**Review by dule8996 — APPROVED** [review]

**Comment by Addicted-Integrity** [comment]
Can someone give me the rundown on w t f this even is? Lol

**Comment by Addicted-Integrity** [comment]
Can someone give me the rundown on w t f this even is ?

**Pull request closed without merging**
